#A pipeline is made up of one or more stages
#A stage is a way of organizing jobs in a pipeline and each stage can have one or more jobs


trigger: none

pool:
  vmimage: 'ubuntu-18.04'

steps:
- script: echo 'Hello world'
