#Continuous integration
#Triggers cause a pipeline to run whenever an update is pushed to the specified branches or specified tags are pushed


trigger:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*
####################################
trigger:
  branches:
    include:
      - refs/tags/{tagname}
    exclude:
      - releases/tags/{othertagname}

#####################################
trigger:
  branches:
    include:
    - '*'